apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-fastapi-app
  labels:
    app: k8s-fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-fastapi-app
  template:
    metadata:
      labels:
        app: k8s-fastapi-app
    spec:
      containers:
      - name: fastapi-app-k8s-tutorial-app
        image: macwdo/fastapi-app-k8s-tutorial-app:latest
        ports:
        - containerPort: 8000

        
        env:
          - name: "TEST_ENV"
            value: "is there something?"

